# Generated by Django 3.1.3 on 2021-01-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='units',
            field=models.CharField(default='grams', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
        ),
    ]
